max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = -135.0 #degrees

[start_pose]
    x = 0.61 #0.56 
    y = 0.88 # BLUE: 1.13->1.4->0.88
    angle = 45.0
[end_pose]
    x = 1.01 #1.03->0.76->0.86
    y = 1.28 #1.6->1.08->1.18
    angle = 45.0

[[internal_points]]
    x = 0.81 #0.66
    y = 1.08 #0.98