max_velocity = 3.0 #m/s
max_acceleration = 2.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = 90.0 #degrees

[start_pose]
    x = 7.37
    y = 7.52
    angle = 270.0
[end_pose]
    x = 5.52
    y = 7.52
    angle = 180.0

[[internal_points]]
    x = 6.18
    y = 7.52