max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = -111.0 #degrees -88.5 for 5 ball position

[start_pose]
    x = 7.757
    y = 2.878  #Was 2.07
    angle = -111.0 #−111 
[end_pose]
    x = 7.00# 6.074 is Center of opp ball
    y = 1.37#1.369 is edge of tape
    angle = -111.0

[[internal_points]]
    x = 7.379
    y = 2.12