max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = -80.0 #degrees -88.5 for 5 ball position

[start_pose]
    x = 7.00
    y = 1.37  #Was 2.07
    angle = -111.0 #−111 
[end_pose]
    x = 9.0# 9.10 is Center of opp ball
    y = 0.65#0.72 is edge of tape
    angle = -80.0 

[[internal_points]]
    x = 8.3 #8.09
    y = 1.06 #1.045