max_velocity = 1.0 #m/s
max_acceleration = 0.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = 90.0 #degrees

[start_pose]
    x = 7.37
    y = 6.97
    angle = 90.0
[end_pose]
    x = 7.37
    y = 7.67
    angle = 90.0

[[internal_points]]
    x = 7.37
    y = 7.32