max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = 136.5 #degrees

[start_pose]
    x = 6.06
    y = 5.17
    angle = 136.5
[end_pose]
    x = 4.94
    y = 6.18
    angle = 136.5

[[internal_points]]
    x = 5.5
    y = 5.675