max_velocity = 2.0 #m/s
max_acceleration = 1.1 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = 46.5 #degrees

[start_pose]
    x = 4.94
    y = 6.18
    angle = 136.5
[end_pose]
    x = 5.99
    y = 7.28
    angle = 46.5

[[internal_points]]
    x = 5.46 #5.46  
    y = 6.73#6.73