max_velocity = 2.0 #m/s
max_acceleration = 1.25 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = 90.0 #degrees

[start_pose]
    x = 5.99
    y = 7.28
    angle = 46.5
[end_pose]
    x = 7.37
    y = 6.97
    angle = 90.0

[[internal_points]]
    x = 6.79
    y = 6.77