max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = -135.0 #degrees

[start_pose]
    x = 0.96 #0.9 -> 1.12 ->1.5->0.89
    y = 1.19 #0.81 -> 1.03 -> 1.41 ->1.26
    angle = 45.0
[end_pose]
    x = 1.09 #1.03 ->1.63 -> 1.02
    y = 1.39 #1.01 -> 1.61 -> 1.46
    angle = 45.0

[[internal_points]]
    x = 1.03 #0.95 -> 0.96
    y = 1.29 #0.86 -> 1.36