max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = -88.5 #degrees

[start_pose]
    x = 7.62
    y = 2.07
    angle = -88.5
[end_pose]
    x = 7.57
    y = 0.58
    angle = -88.5

[[internal_points]]
    x = 7.60
    y = 1.57