max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 2.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = -135.0 #degrees

[start_pose]
    x = 5.06
    y = 1.87
    angle = -156.0
[end_pose]
    x = 1.16
    y = 1.21
    angle = -135.0

[[internal_points]]
    x = 3.0
    y = 2.0