max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = -156 #degrees

[start_pose]
    x = 7.58
    y = 0.68
    angle = -88.5
[end_pose]
    x = 5.06
    y = 1.87
    angle = -156

[[internal_points]]
    x = 5.82
    y = 2.26