max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 2.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = true
target_yaw = -135.0 #degrees

[start_pose]
    x = 5.06
    y = 1.87
    angle = -156.0
[end_pose]
    x = 1.29
    y = 1.32
    angle = 45.0

[[internal_points]]
    x = 3.78
    y = 2.634